DROP TABLE IF EXISTS "calibrations";
CREATE TABLE "calibrations" ("calibration_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" TEXT);
INSERT INTO "calibrations" VALUES(1,'test1');
INSERT INTO "calibrations" VALUES(4,'third');
DROP TABLE IF EXISTS "learned_functions";
CREATE TABLE "learned_functions" ("lf_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "theta0" DOUBLE, "theta1" DOUBLE, "theta2" DOUBLE, "theta3" DOUBLE, "calibration_id_fk" INTEGER);
DROP TABLE IF EXISTS "learned_points";
CREATE TABLE "learned_points" ("lp_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "x" DOUBLE, "y" DOUBLE, "calibration_id_fk" INTEGER);
INSERT INTO "learned_points" VALUES(1,1,1.2,1);
INSERT INTO "learned_points" VALUES(2,1.5,1.8,1);
INSERT INTO "learned_points" VALUES(3,2.1,2.5,1);
INSERT INTO "learned_points" VALUES(4,0.1,0.05,1);
DROP TABLE IF EXISTS "measurements";
CREATE TABLE "measurements" ("measurements_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "time" DOUBLE, "fibrinogen" DOUBLE, "calibration_id_fk" INTEGER);
INSERT INTO "measurements" VALUES(3,3,0.5,1);
INSERT INTO "measurements" VALUES(4,1,1,1);
