DROP TABLE IF EXISTS "calibrations";
CREATE TABLE "calibrations" ("calibration_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" TEXT);
INSERT INTO "calibrations" VALUES(1,'test1');
INSERT INTO "calibrations" VALUES(4,'third');
DROP TABLE IF EXISTS "learned_functions";
CREATE TABLE "learned_functions" ("lf_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "theta0" DOUBLE, "theta1" DOUBLE, "theta2" DOUBLE, "theta3" DOUBLE, "calibration_id_fk" INTEGER, "mean1" DOUBLE, "mean2" DOUBLE, "mean3" DOUBLE, "range1" DOUBLE, "range2" DOUBLE, "range3" DOUBLE);
INSERT INTO "learned_functions" VALUES(13,1.25,2.3679870724663252,0.3449311033002753,-0.2238796090977505,1,1.25,2.2916666666666665,4.6875,2.5,2.5,2.5);
DROP TABLE IF EXISTS "learned_points";
CREATE TABLE "learned_points" ("lp_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "x" DOUBLE, "y" DOUBLE, "calibration_id_fk" INTEGER);
INSERT INTO "learned_points" VALUES(1,1,1.2,1);
INSERT INTO "learned_points" VALUES(2,1.5,1.8,1);
INSERT INTO "learned_points" VALUES(3,2.1,2.5,1);
INSERT INTO "learned_points" VALUES(4,0.1,0.05,1);
DROP TABLE IF EXISTS "measurements";
CREATE TABLE "measurements" ("measurements_id_pk" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "time" DOUBLE, "fibrinogen" DOUBLE, "calibration_id_fk" INTEGER);
INSERT INTO "measurements" VALUES(7,2,2,1);
INSERT INTO "measurements" VALUES(8,2.5,2.5,1);
INSERT INTO "measurements" VALUES(9,1.5,1.5,1);
INSERT INTO "measurements" VALUES(14,1,1,1);
INSERT INTO "measurements" VALUES(15,0.5,0.5,1);
INSERT INTO "measurements" VALUES(16,0,0,1);
